const VOXEL_TYPE = {
	AIR: 255,
	WATER: 254,
	OUTSIDE_WORLD: 253
};

const WATER_SURFACE_HEIGHT = 8;

const CHUNK_SIZE = {x: 16, y: 96, z: 16};
const NUMBER_OF_CHUNKS = {x: 2, y: 1, z: 2};

const WORLD_SIZE = {x: CHUNK_SIZE.x * NUMBER_OF_CHUNKS.x,
					y: CHUNK_SIZE.y * NUMBER_OF_CHUNKS.y,
					z: CHUNK_SIZE.z * NUMBER_OF_CHUNKS.z };

const NUMBER_OF_VOXELS_PER_CHUNK = CHUNK_SIZE.x * CHUNK_SIZE.y * CHUNK_SIZE.z;
const NUMBER_OF_VOXELS_IN_WORLD = NUMBER_OF_VOXELS_PER_CHUNK * NUMBER_OF_CHUNKS.x * NUMBER_OF_CHUNKS.y * NUMBER_OF_CHUNKS.z;

const VOXEL_SIDE_LENGTH = 1;
const VOXEL_HALF_SIDE_LENGTH = VOXEL_SIDE_LENGTH / 2;

const MAXIMUM_PICKING_RANGE = 25;

const DWARF_MOVING_SPEED = 3 / 60;